IF DB_ID (N'githubdb') IS NULL
create database githubdb
GO

USE githubdb;

IF OBJECT_ID('dbo.T_AUTHORS', 'U') IS NOT NULL DROP TABLE dbo.T_AUTHORS;

CREATE TABLE dbo.T_AUTHORS
(
  ID_AUTHOR   INT         NOT NULL IDENTITY(1, 1)
    CONSTRAINT PK_AUTHORS PRIMARY KEY,
  LOGIN NVARCHAR(30)        NOT NULL,
  AVATAR    NVARCHAR(MAX) NOT NULL
);
GO

IF OBJECT_ID('dbo.T_REPO', 'U') IS NOT NULL DROP TABLE dbo.T_REPO;

CREATE TABLE dbo.T_REPO
(
  ID_REPO   INT         NOT NULL IDENTITY(1, 1)
    CONSTRAINT PK_REPO PRIMARY KEY,
  REPO_NAME NVARCHAR(50)        NOT NULL,
  REPO_DESC NVARCHAR(MAX),
  AUTHOR_ID INT NOT NULL,
  REPO_REF NVARCHAR(MAX),
  LANGUAGE NVARCHAR(30),
  STARS_COUNT INT NOT NULL,
  FORKS_COUNT INT NOT NULL,
  DATE_UPDATE datetime NOT NULL
);
GO