//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookingForRepos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REPO
    {
        public int ID_REPO { get; set; }
        public string REPO_NAME { get; set; }
        public string REPO_DESC { get; set; }
        public int AUTHOR_ID { get; set; }
        public string REPO_REF { get; set; }
        public string LANGUAGE { get; set; }
        public int STARS_COUNT { get; set; }
        public int FORKS_COUNT { get; set; }
        public System.DateTime DATE_UPDATE { get; set; }
    
        public virtual T_AUTHORS T_AUTHORS { get; set; }
    }
}
